all:
	cd cdt; make
	cd common; make
	cd gvc; make
	cd pathplan; make
	cd graph; make
	cd pack; make
	cd sparse; make
	cd rbtree; make
	cd ortho; make
	cd neatogen; make
	cd dotgen; make
	cd sfdpgen; make

clean:
	cd cdt; make clean
	cd common; make clean
	cd gvc; make clean
	cd pathplan; make clean
	cd graph; make clean
	cd pack; make clean
	cd sparse; make clean
	cd rbtree; make clean
	cd ortho; make clean
	cd neatogen; make clean
	cd dotgen; make clean
	cd sfdpgen; make clean
